/**
 * Maps Firestore (Italian) team names → possible API-Football (English) variants.
 * Keep in sync with functions/src/fetchResults.ts.
 */
export const teamAliases: Record<string, string[]> = {
  // Hosts + Nord America
  "USA": ["United States", "USA"],
  "Messico": ["Mexico"],
  "Canada": ["Canada"],
  // Sud America
  "Brasile": ["Brazil"],
  "Argentina": ["Argentina"],
  "Colombia": ["Colombia"],
  "Uruguay": ["Uruguay"],
  "Paraguay": ["Paraguay"],
  "Ecuador": ["Ecuador"],
  "Cile": ["Chile"],
  "Perù": ["Peru"],
  "Venezuela": ["Venezuela"],
  // Europa
  "Italia": ["Italy"],
  "Germania": ["Germany"],
  "Francia": ["France"],
  "Spagna": ["Spain"],
  "Inghilterra": ["England"],
  "Portogallo": ["Portugal"],
  "Olanda": ["Netherlands", "Holland"],
  "Belgio": ["Belgium"],
  "Croazia": ["Croatia"],
  "Danimarca": ["Denmark"],
  "Serbia": ["Serbia"],
  "Svizzera": ["Switzerland"],
  "Polonia": ["Poland"],
  "Norvegia": ["Norway"],
  "Svezia": ["Sweden"],
  "Scozia": ["Scotland"],
  "Galles": ["Wales"],
  "Austria": ["Austria"],
  "Repubblica Ceca": ["Czech Republic", "Czechia"],
  "Bosnia-Erzegovina": ["Bosnia and Herzegovina", "Bosnia & Herzegovina", "Bosnia"],
  "Turchia": ["Turkey", "Türkiye"],
  // Asia
  "Giappone": ["Japan"],
  "Corea del Sud": ["South Korea", "Korea Republic"],
  "Australia": ["Australia"],
  "Iran": ["Iran", "IR Iran"],
  "Arabia Saudita": ["Saudi Arabia"],
  "Qatar": ["Qatar"],
  "Iraq": ["Iraq"],
  "Giordania": ["Jordan"],
  "Uzbekistan": ["Uzbekistan"],
  // Africa
  "Marocco": ["Morocco"],
  "Senegal": ["Senegal"],
  "Egitto": ["Egypt"],
  "Tunisia": ["Tunisia"],
  "Algeria": ["Algeria"],
  "Ghana": ["Ghana"],
  "Sudafrica": ["South Africa"],
  "Costa d'Avorio": ["Ivory Coast", "Cote D'Ivoire", "Côte d'Ivoire"],
  "Capo Verde": ["Cape Verde", "Cabo Verde"],
  "RD Congo": ["DR Congo", "Democratic Republic of Congo", "Congo DR"],
  "Nigeria": ["Nigeria"],
  "Camerun": ["Cameroon"],
  // Oceania
  "Nuova Zelanda": ["New Zealand"],
  // Centro America / Caraibi
  "Panama": ["Panama"],
  "Haiti": ["Haiti"],
  "Curaçao": ["Curacao", "Curaçao"],
  "Costa Rica": ["Costa Rica"],
  "Honduras": ["Honduras"],
  "Israele": ["Israel"],
};
