export type Sign = "1" | "X" | "2";

export type ScheduleStatus = "bozza" | "inviata" | "accettata" | "rifiutata";

export type Phase = "gironi" | "ottavi" | "quarti" | "semifinali" | "finale";

export interface Game {
  id: string;
  name: string;
  entryFee: number;
  admins: string[];
  adminCode: string;
  accessCode: string;
  phases: Phase[];
  currentPhase: Phase;
  topScorer: string | null;
  winner: string | null;
}

/**
 * Where did the kickoff date come from?
 * - "synthetic": generated by the initial seed (placeholder — needs to be updated)
 * - "api": fetched from API-Football (authoritative FIFA schedule)
 * - "manual": set explicitly by an admin via the Risultati page (never overwrite)
 */
export type KickoffSource = "synthetic" | "api" | "manual";

export interface Match {
  id: string;
  phase: Phase;
  group: string | null;
  homeTeam: string;
  awayTeam: string;
  kickoff: Date;
  kickoffSource?: KickoffSource;
  result: Sign | null;
  score: string | null;
  locked: boolean;
}

export interface Player {
  id: string;
  name: string;
  joinedAt: Date;
  predictions: Record<string, Sign>;
  topScorerPick: string;
  winnerPick: string;
  points: number;
  paid: boolean;
  scheduleStatus: ScheduleStatus;
}
