import type { Timestamp } from 'firebase/firestore';

export type Sign = "1" | "X" | "2";
export type QualifierSign = "1" | "2";

export type ScheduleStatus = "bozza" | "inviata" | "accettata" | "rifiutata";

export type GameMode = "classic" | "golden-plus";
export type PredictionMode = "result" | "qualifier";

export type Phase = "gironi" | "sedicesimi" | "ottavi" | "quarti" | "semifinali" | "finale";

export interface Game {
  id: string;
  name: string;
  entryFee: number;
  admins: string[];
  adminPlayerUids?: Record<string, string>;
  playerDeviceAliases?: Record<string, string>;
  accessCode: string;
  adminCode?: string;
  adminCodeHash?: string;
  lockLeadHours?: number;
  phaseLockLeadHours?: Partial<Record<Phase, number>>;
  phases: Phase[];
  currentPhase: Phase;
  topScorer: string | null;
  winner: string | null;
  mode?: GameMode;
  predictionMode?: PredictionMode;
  specialPicksEnabled?: boolean;
  sourceGameId?: string;
  accessClosesAt?: Date;
}

/**
 * Where did the kickoff date come from?
 * - "synthetic": generated by the initial seed (placeholder — needs to be updated)
 * - "api": fetched from API-Football (authoritative FIFA schedule)
 * - "manual": set explicitly by an admin via the Risultati page (never overwrite)
 */
export type KickoffSource = "synthetic" | "api" | "manual";

export interface Match {
  id: string;
  phase: Phase;
  group: string | null;
  homeTeam: string;
  awayTeam: string;
  kickoff: Date;
  kickoffSource?: KickoffSource;
  result: Sign | null;
  score: string | null;
  locked: boolean;
  bracketSlot?: string;
  feedsInto?: string | null;
  feedsIntoSide?: "home" | "away" | null;
}

export interface Player {
  id: string;
  name: string;
  joinedAt: Date;
  predictions: Record<string, Sign>;
  topScorerPick: string;
  winnerPick: string;
  points: number;
  /** Leaderboard rank held just before the most recent points recalc.
   *  Used to show movement arrows in the standings. null/undefined = no
   *  prior snapshot yet (e.g. before the first result, or a new player). */
  previousRank?: number | null;
  paid: boolean;
  scheduleStatus: ScheduleStatus;
  multiDeviceEnabled?: boolean;
  deviceUids?: string[];
  lastAnnouncementReadAt?: Timestamp | null;
}

export type AnnouncementStatus = 'draft' | 'published';

export type Announcement = {
  id: string;
  title: string;
  body: string;
  status: AnnouncementStatus;
  authorUid: string;
  targetUids: string[] | null;
  createdAt: Timestamp;
  publishedAt: Timestamp | null;
  editedAt: Timestamp | null;
  deletedAt: Timestamp | null;
};

export type ChatFrom = 'player' | 'committee';

export type Thread = {
  playerUid: string;
  playerName: string;
  lastMessageAt: Timestamp;
  lastMessagePreview: string;
  lastMessageFrom: ChatFrom;
  unreadByPlayer: number;
  unreadByCommittee: number;
};

export type ChatMessage = {
  id: string;
  text: string;
  from: ChatFrom;
  senderUid: string;
  createdAt: Timestamp;
};

export type GoldenAccessStatus = "pending" | "approved" | "rejected" | "revoked";
export type GoldenAccessType = "classic-player" | "new-request";

export interface GoldenAccess {
  id: string;
  status: GoldenAccessStatus;
  type: GoldenAccessType;
  displayName: string;
  contact?: string;
  classicPlayerUid?: string;
  authUids?: string[];
  paid?: boolean;
}

export const ANNOUNCEMENT_TITLE_MAX = 120;
export const ANNOUNCEMENT_BODY_MAX = 2000;
export const CHAT_MESSAGE_MAX = 1000;
export const CHAT_PREVIEW_MAX = 80;
export const PUSH_BODY_MAX = 140;
