import type { Timestamp } from 'firebase/firestore';

export type Sign = "1" | "X" | "2";

export type ScheduleStatus = "bozza" | "inviata" | "accettata" | "rifiutata";

export type Phase = "gironi" | "ottavi" | "quarti" | "semifinali" | "finale";

export interface Game {
  id: string;
  name: string;
  entryFee: number;
  admins: string[];
  accessCode: string;
  adminCode?: string;
  adminCodeHash?: string;
  phases: Phase[];
  currentPhase: Phase;
  topScorer: string | null;
  winner: string | null;
}

/**
 * Where did the kickoff date come from?
 * - "synthetic": generated by the initial seed (placeholder — needs to be updated)
 * - "api": fetched from API-Football (authoritative FIFA schedule)
 * - "manual": set explicitly by an admin via the Risultati page (never overwrite)
 */
export type KickoffSource = "synthetic" | "api" | "manual";

export interface Match {
  id: string;
  phase: Phase;
  group: string | null;
  homeTeam: string;
  awayTeam: string;
  kickoff: Date;
  kickoffSource?: KickoffSource;
  result: Sign | null;
  score: string | null;
  locked: boolean;
}

export interface Player {
  id: string;
  name: string;
  joinedAt: Date;
  predictions: Record<string, Sign>;
  topScorerPick: string;
  winnerPick: string;
  points: number;
  paid: boolean;
  scheduleStatus: ScheduleStatus;
}

export type AnnouncementStatus = 'draft' | 'published';

export type Announcement = {
  id: string;
  title: string;
  body: string;
  status: AnnouncementStatus;
  authorUid: string;
  targetUids: string[] | null;
  createdAt: Timestamp;
  publishedAt: Timestamp | null;
  editedAt: Timestamp | null;
  deletedAt: Timestamp | null;
};

export type ChatFrom = 'player' | 'committee';

export type Thread = {
  playerUid: string;
  playerName: string;
  lastMessageAt: Timestamp;
  lastMessagePreview: string;
  lastMessageFrom: ChatFrom;
  unreadByPlayer: number;
  unreadByCommittee: number;
};

export type ChatMessage = {
  id: string;
  text: string;
  from: ChatFrom;
  senderUid: string;
  createdAt: Timestamp;
};

export const ANNOUNCEMENT_TITLE_MAX = 120;
export const ANNOUNCEMENT_BODY_MAX = 2000;
export const CHAT_MESSAGE_MAX = 1000;
export const CHAT_PREVIEW_MAX = 80;
export const PUSH_BODY_MAX = 140;
